Added GHA test for hardcoded filenames

diff --git a/.github/workflows/fcb_autograding.yml b/.github/workflows/fcb_autograding.yml
--- a/.github/workflows/fcb_autograding.yml
+++ b/.github/workflows/fcb_autograding.yml
@@ -10,11 +10,15 @@ jobs:
     steps:
       - uses: actions/checkout@v3
       - name: Set up Python modules
-        run: sudo -H pip3 install pytest pytest-timeout pandas
+        run: sudo -H pip3 install pytest pytest-timeout
+      - name: Checking for academic integrity statement
+        run: RED='\033[0;31m'; NC='\033[0m' ; x=`grep 'The work here submitted' README.md | perl -nae 'print $F[1]'` ; if [ "$x" != [X] ] && [ "$x" != [x] ] ; then { if [ "$x" == [\"X\"] ] || [ "$x" == [\'X\'] ] || [ "$x" == [\"x\"] ] || [ "$x" == [\'x\'] ] ; then echo -e "${RED}DO NOT USE QUOTE CHARACTERS WHEN CHECKING THE ACADEMIC INTEGRITY STATEMENT${NC}" ; else echo -e "${RED}YOU HAVE NOT YET AGREED TO THE ACADEMIC INTEGRITY STATEMENT (SEE README.md FILE)${NC}" ; fi ; exit 1 ; } ; fi
       - name: Checking for syntax errors
         run: python3 -m py_compile src/dinuc.py ; rm -f src/dinuc.pyc
       - name: Checking for HBB.fa
-        run: if [ -e HBB.fa ] ; then { if [ `md5sum HBB.fa | cut -d ' ' -f 1` == "82d645e7436e7931155ba305c0160eb9" ] ; then exit 0 ; else { echo WRONG FILE HBB.fa ; exit 1 ; } fi } ; else { echo MISSING FILE HBB.fa ; exit 1 ; } ; fi
+        run: RED='\033[0;31m'; NC='\033[0m' ; if [ -e HBB.fa ] ; then { if [ `md5sum HBB.fa | cut -d ' ' -f 1` == "82d645e7436e7931155ba305c0160eb9" ] ; then exit 0 ; else { echo -e "${RED}WRONG FILE HBB.fa${NC}" ; exit 1 ; } fi } ; else { echo "${RED}MISSING FILE HBB.fa${NC}" ; exit 1 ; } ; fi
+      - name: Checking for opening a hardcoded filename
+        run: RED='\033[0;31m'; NC='\033[0m' ; nlhcfname=`egrep -n 'open\("[^"]+"\)' tmp.py | head -1 | cut -d ':' -f 1` ; if [ $nlhcfname -gt 0 ] ; then { echo -e "${RED}YOU ARE OPENING A FASTA FILE WITH A HARDCODED FILENAME IN LINE $nlhcfname INSTEAD OF TAKING THE FILENAME AS AN ARGUMENT FROM THE COMMAND LINE (SEE README.md FILE)${NC}" ; exit 1 ; } ; else { exit 0 ; } ; fi
       - name: Calculate gold standard
         run: grep -v '>' HBB.fa | tr -d '\n' | fold -2 | grep -v '^.$'| sort | uniq -c | sort -k 2 | sed 's/^[[:space:]]*//;s/ /,/;1i N,DNT' > dinucgold1.csv ; grep -v '>' HBB.fa | tr -d '\n' | sed 's/^.//' | fold -2 | grep -v '^.$' | sort | uniq -c | sort -k 2 | sed 's/^[[:space:]]*//;s/ /,/;1i N,DNT' > dinucgold2.csv
       - name: Run autograding tests
